### PR TITLE
fix: cache only http resources

### LINKED ISSUE #161: Board fails to load after login (refresh required)
__Describe the Bug__

Given I am signed off, when I log in, the board fails to load and I have to refresh the page. It works fine afterwards.

I checked the developer tools and found this message:

```
service-worker.js:1 Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Request scheme 'chrome-extension' is unsupported
    at service-worker.js:1:375
```

So it looks like the service worker code cannot handle chrome extensions correctly. The extensions I have are:

* Keeper
* Torii
* Okta
* Zoom Now (doesn't have access to tasks.bpmn.io)

__Steps to Reproduce__

See the description.

__Expected Behavior__

Board should load.

__Environment__

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Board version: [e.g. 1.0.0]

### PR DESCRIPTION
**Pull request by barmac**
Closes #161

### CODE REVIEW

File: packages/board/src/service-worker.js [hunk 1]
```diff
@@ -21,6 +21,12 @@ function precache() {
 }
 
 function cacheResponse(event, request, response) {
+  const parsedUrl = new URL(request.url);
+
+  // only cache http resources
+  if (!/^https?:$/.test(parsedUrl.protocol)) {
+    return;
+  }
```
Comment (nikku) [inline packages/board/src/service-worker.js:29]:
```suggestion
  // only cache http(s) resources
  if (!/^https?:$/.test(request.url)) {
    return;
  }
```

File: packages/board/src/service-worker.js [hunk 2]
```diff
@@ -21,6 +21,10 @@ function precache() {
 }
 
 function cacheResponse(event, request, response) {
+  // only cache http(s) resources
```
Comment (nikku) [inline packages/board/src/service-worker.js:24]:
```suggestion

  // only cache http(s) resources
```

**Comment by barmac** [comment]
I did not verify this locally but assumed it should work.
